export const triggerList = [
    "Crelly gets one-guyed",
    "Crom mentioned",
    "Crister mentioned",
    "Crelly is suspicious of Throne gifts", 
    "⁎Turns a TTS into a 'deez nuts' joke⁎",
    "Crelly simps for a mod",
    "Chat simps for a mod",
    "Crelly accuses chat of caring about her",
    "Chat brings Crelly to tears",
    "\"Let's fucking shit!\"",
    "⁎Get's mad at a new Koko meme⁎",
    "Accuses chat of being coomers",
    "Crelly tries and fails to be mean",
    "Plate-tonic",
    "*Screams*: Koko halp!",
    "\"Don't worry, we have **eight hours** left...\"",
    "\"I miss [someone who left five seconds ago]\"",
    "Is just an <Sub>impossibly small</sub> guy",
    "Brings up gooning unprompted",
    "⁎Refuses to acknowledge Cremen despite talking about them more than all other groups⁎",
    "\"That's crazy. That's *crazy*. That's so **crazy**\"",
    "\"Can I ask you a question?\" x3",
    "Parasocial bating chat",
    "Parasocially calls out clipper",
    "Is it working?",
    "Talks about piss unprompted",
    "Is it against ToS to do this?",
    "Mods! Mods! Dink Donk Dink Donk",
    "Crelly writes Viewer/Crelly fanfic out loud",
    "Timmy is sent back to the mines",
    "G-Go-G-G-Gottem... (she don't gottem)",
    "⁎Stutters so hard she gives up⁎",
    "Press 3 for delicious Burger King Whopper",
    "Someone other than Crelly shells the GamerSupps code, get 10% off all your gamersupp—",
    "Crazy? I was crazy once. They locked me in a room. A *rubber* room. With rats. Rats make me crazy.",
    "Says something disgusting, and is surprised ppl think it's disgusting",
    "Cuck",
    "Wasps. Just wasps.",
    "Mentions not showering",
    "Jeffing all over the place",
    "Crelly is *surprisingly* competent at something",
    "Plays a game",
    "Brings up vore unprompted",
    "Crelly forgets something",
    "Crelly remembers something she forgot ten minutes later",
    "Says \"BuhFlipExplode\"",
    "Hiccups",
    "Tries to convince chat she's a top/dom",
    "Draws on the screen",
    "We don't talk about the bald debt",
    "Crelly reacts to Crelly",
    "Deep voice",
    "*Visceral disgust* at a scan",
    "\"Put 'em up!   ...wait no–",
    "\"Delete the VOD\"!",
];